modLoader="javafml"
loaderVersion="[4,)"
license="MIT"


[[mixins]]
    config="betteritemvaults.mixins.json"

[[mixins]]
    config="betteritemvaults.create_connected.mixins.json"

[[mixins]]
    config="betteritemvaults.dndecor.mixins.json"

[[mods]]
    modId="betteritemvaults"
    version="1.0.1"
    displayName="Better Item Vaults"
    description="Forces vaults to hold 1280 single items instead of stacks."

[[dependencies.betteritemvaults]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betteritemvaults]]
    modId="create"
    type="required"
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.betteritemvaults]]
    modId="create_connected"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.betteritemvaults]]
    modId="dndecor"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
