modLoader="neoforged"
loaderVersion="[21,)"
license="MIT"

[[mixins]]
    config="betteritemvaults.mixins.json"

[[mods]]
    modId="betteritemvaults"
    version="1.0.0"
    displayName="Better Item Vaults"
    description="Forces vaults to hold 1280 single items instead of stacks."

[[dependencies.betteritemvaults]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betteritemvaults]]
    modId="create"
    type="required"
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"
